### ISSUE TITLE
I can not control the stripe over the webinterface

### ISSUE THREAD

**Issue by mischa67** [kevkid/led_strip#1]
Hi,

i can start the program with 'sudo python lights.py' without problems.
I also can call the webpage but the controls do not work.

I have tested the audio-reactive-led-strip project with the modifications for ws2801 (issue #123) and it works fine. 

Any Ideas what can be the problem?

Thanks
Henri

**Comment by kevkid** [comment]
Can you check the console in chrome (or another browser) its probably jquery and bootstrap may be missing? I have a feeling its failing at the ajax call.

**Comment by mischa67** [comment]
On the console i get

TypeError: $.ajax is not a function

**Comment by kevkid** [comment]
Make sure jquery.js is in the static folder. Otherwise ill have to take a closer look at it when I am home. Can you post a screenshot of the error?

**Comment by mischa67** [comment]
jquery.js is in the static folder.

here is the screenshot
![ajax-error](https://user-images.githubusercontent.com/37514356/37687813-553a3ea6-2c9d-11e8-9ea3-ce5c50601eb7.jpg)

**Comment by mischa67** [comment]
I think the problem is the the jquery.slim call. I have changed to without .slim and it works.

**Comment by ghost** [comment]
Hi 
I have the same issue but I am getting another error
the Debugger says 
![issue](https://user-images.githubusercontent.com/38256913/38821002-a8cf93ec-419f-11e8-9d9a-0f66a7cc90e5.png)
![issue2](https://user-images.githubusercontent.com/38256913/38820772-0fd4f1aa-419f-11e8-80dc-10f59a91aea0.png)

What can I do to get it running ?

**Comment by kevkid** [comment]
You need to install jquery. You can also use a cdn. I didnt include it
because of licensing issues.

**Comment by ghost** [comment]
okay I already installed it but nothing has changed but i will try it again
thanks for the quick reply

**Comment by kevkid** [comment]
Do you get the same error? Try restarting the server.

**Comment by ghost** [comment]
I have restarted the Server and nothing has changed the same error again

**Comment by ghost** [comment]
I have tried to reinstall jquery from github and i am getting this error Messages 
![issue3](https://user-images.githubusercontent.com/38256913/38826326-b9f0c47e-41af-11e8-8879-4323532b4d82.png)

**Comment by kevkid** [comment]
Try using the CDN in template/index.html. There should be a script call to jquery. Try replacing the line to this:

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

Then restart the server.

**Comment by ghost** [comment]
I tried this and now i am getting another error
![issue4](https://user-images.githubusercontent.com/38256913/38827386-0857a0d0-41b3-11e8-9f5c-064613e3185b.png)

**Comment by kevkid** [comment]
Hrmm, Looks like you are getting a 404 error when doing an ajax call... Looks like you tried to click on a color and it fails? I am wondering, can you kill all of your python (sudo killall python) then re-run the script as sudo?

It should work, not exactly sure what is causing you to get a 404.

**Comment by ghost** [comment]
I tried to kill all python processes but no processes were running then I tried to run the script again and I get the same error. I cant even run the visualisation over the webinterface but wehen I try to run the visualisazion.py over commandline everything works fine. What else can I try to get it running ?

**Comment by kevkid** [comment]
Can you translate the error that you are getting?

**Comment by ghost** [comment]
Sry I forgot that this error message was on German 

HTTP404: NOT FOUND: The server found no matches for the requested URI (Uniform Resource Identifier)  (XHR)POST  - http://MY_IP_ADRESS/getColor

The error message varies when i try other Buttons then  the getColor becomes useFunction

**Comment by kevkid** [comment]
Interesting. So your ip address, I assume you are blocking it because it is the ip that your ISP gives you right? not your local one? (looks like 192.x.x.x or 10.x.x.x). I think the reason it is not connecting (giving you a 404) is because you are accessing it via the wan IP address (or for some reason its routing you to your wan ip address).

Here is something to try. Since this is on your raspberry pi run the script. I am assuming that you pi is on your local network. Try on your phone or computer (separate from the pi) to connect to the pi via the local address. You also want to make sure when you connect that you are using port 8080 (you can change this if you want via the lights.py). Are you able to access the server via the local ip address? How about trying to change a color or something do you get the same issue?

**Comment by ghost** [comment]
Thanks Thanks Thanks now it is working i forgot to connect via port 8080 but on my iPhone the Buttons are not showing in the right order and design what do i have to Change to correct this ?

**Comment by kevkid** [comment]
Hrmm, Does it work properly on any other device other than your iphone?

**Comment by ghost** [comment]
It sems to work properly on any other device what Could be the Problem ?
The css ?

kevkid <notifications@github.com> schrieb am Mo. 16. Apr. 2018 um 23:36:

**Comment by kevkid** [comment]
interesting. I do not have an iphone to test on unfortunately. Can you
kindly post a screenshot of what you see on your iphone? Maybe try a
different browser? try clearing the cache on your iphones browser?

**Comment by ghost** [comment]
I have Tester it on anzöget Browser But for me this made no difference Here
is the screenshot

![issue5](https://user-images.githubusercontent.com/38256913/38953559-67426d9e-434f-11e8-80b2-92ec2606f70d.JPG)


kevkid <notifications@github.com> schrieb am Mi. 18. Apr. 2018 um 21:21:

**Comment by kevkid** [comment]
Ah, maybe it has something to do with bootstrap? you said your browser on your computer displays it properly, but just on your iphone it doesn't work? Maybe it isn't downloading or interpreting bootstrap on your phone?

**Comment by kevkid** [comment]
Did you ever solve it?

**Comment by ghost** [comment]
Sry that i don’t have anderes your question

Of Course i have Solved it and it Works Amazing the only thing i would like
to Build is an spotify connect Server linked with it but i don’t know How
to do that.

In the end your Project works totaly Fine and i am happy about this. Thanks
für that Project


kevkid <notifications@github.com> schrieb am Di. 19. Juni 2018 um 21:38:

**Comment by kevkid** [comment]
Glad I could help! And glad you enjoy the project. Let me know if you need anymore help.

Since problem is solved, closing thread.
